FROM ruby:3.2.3
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.jsとYarnのリポジトリキーを追加し、インストール
RUN apt-get update -qq \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && NODE_MAJOR=20 \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# 必要なパッケージをインストール
RUN apt-get update -qq && apt-get install -y build-essential libssl-dev nodejs yarn vim

# 作業ディレクトリを作成
RUN mkdir /myapp
WORKDIR /myapp

# Bundlerをインストール
RUN gem install bundler

# アプリケーションコードをコピー
COPY . /myapp

# Yarnの依存関係をインストール
RUN yarn install

# esbuildとtailwindcssをグローバルにインストール
RUN yarn global add esbuild tailwindcss

# 必要なGemをインストール
RUN bundle install
